[socat]
dest_host = "127.0.0.1"
dest_port = 7778

[server]
host = ""
gameport = 7777
queryport = 27015
appid = 480
gamedir = ""
version = ""
server_name = ""
game_name = ""
map = ""
protocol = 0
players = 0
max_players = 0
num_bots = 0
region = "255"
dedicated = true
os = "w"
product = ""
server_type = "d"
secure = true
keywords = ""
steamid = 0
password_protected = false

[rules]
key = "value_pair1"
key2 = "vaue_pair2"
free = "form data here"

[players]
# TODO: player advertising strategies.
#   - Increment score and time played to mimic actual gameplay.
strategy = "dynamic"  # One of "dynamic", "static".
game = "generic"  # "Generic" or "rs2".
names = [
    "foo",
    "bar",
    "baz",
]
